# @package _group_
protocol: 'ond'
workdir: '~/code/sail-on-project/sailon_tinker_launcher/workdir'
harness: 'local'
domain: activity_recognition
test_ids:
  - OND.11355983.36308137.2192
hints:
  - "red_light"
dataset_root: "/home/ameya/data/TA1-activity-recognition/videos"
use_saved_features: True
use_consolidated_features: True
save_dir: "/data/SAIL-ON/TA1-activity-recognition-self-eval/activity-recognition/features"
use_feedback: True
is_eval_enabled: True
is_eval_roundwise_enabled: True
detectors:
  has_baseline: False
  has_reaction_baseline: True
  csv_folder: activity_recognition
  baseline_class: 'baseline_i3d'
  cores: 6
  detection_threshold: 0.5
  detector_configs:
    x3d_rd:
      feature_extractor_params:
        x3d_version: "M"
        num_classes: 88
        num_channels: 3
        dropout: 1.0
        base_bn_splits: 1
        resnet_shortcut: "B"
        checkpoint_path: "/home/ameya/models/activity-recognition-models/x3d/x3d_ta2_rgb_sgd_best.pt"
      kl_params:
        window_size: 100
        mu_train: 1.0
        sigma_train: 0.109234035
        KL_threshold: 2.2821471417278874
        feedback_weight: 0.005
      evm_params:
        model_path:  '/home/ameya/models/activity-recognition-models/x3d/x3d_feats_evm.pkl'
        distance_function: 'cosine'
        gpu_idx: 0
      characterization_params:
        clustering_type: FINCH
        number_of_unknown_to_strat_clustering: 50
      dataloader_params:
        norm_value: 255.0
        spatial_size: 224
        frames: 80
        gamma_tau: 5
        mean:
          - 0
          - 0
          - 0
        std:
          - 1
          - 1
          - 1
        crops: 10
        batch_size: 1
        n_threads: 2
      feedback_params:
          first_budget: 4
          income_per_batch: 4
          maximum_budget: 4
    baseline_i3d:
      feature_extractor_params:
        backbone_weight_path: '/home/ameya/models/graph-autoencoder/save_best.pth'
        name: i3d
        arch: i3d-50
        model_name: i3d
        n_classes: 88
        no_cuda: 'False'
        hidden_dims:
          - 512
          - 128
        hidden: 'True'
        in_dim: 1024
        num_heads:
          - 4
          - 1
        sample_duration: 64
        mode: score
        graph_classes: 88
        feature_type: graph
      dataloader_params:
        sample_size: 224
        mean:
          - 114.7748
          - 107.7354
          - 99.475
        sample_duration: 64
        batch_size: 1
        n_threads: 2
        n_classes: 88
harness_config:
  url: 'http://3.32.8.161:5001/'
  data_dir: '/data/SAIL-ON/TA1-activity-recognition-self-eval/activity-recognition/early_960-samples_20-groups_5-runs'
  gt_dir: '/data/SAIL-ON/TA1-activity-recognition-self-eval/activity-recognition/early_960-samples_20-groups_5-runs/OND/activity_recognition'
  gt_config: '/home/ameya/code/sail-on-project/sail-on-client/tests/data/OND/activity_recognition/activity_recognition.json'
