# @package _group_
protocol: 'condda'
workdir: ''
harness: 'local'
domain: image_classification
test_ids:
- OND.54011215.0000.1236
hints:
- red_light
dataset_root: ""
detectors:
  has_reaction_baseline: 'False'
  has_baseline: 'False'
  cores: 6
  detector_configs:
    CONDDA_18_With_Redlight:
      cnn_params:
          model_path: ""
          known_classes: 413
          known_unknown_classes: 51
          image_size: 320
      evm_params:
         model_path: ""
         feature_known_path: ""
         tail_size: 40000
         cover_threshold: 0.8
         distance_multiplier: 0.65
         unknown_distance_multiplier: 0.80
         distance_function: "cosine"
         chunk_size: 200
         gpu_list:
           - 0
           - 1
         mu_train: 1.0
         sigma_train: 0.028588828
         KL_threshold: 62.855897282606946
         threshold_evm: 0.5
         number_of_unknown_to_crate_evm: 10
      characterization_param:
         clustering_type: "FINCH"
         number_of_unknown_to_strat_clustering: 100
         minimum_number_of_cluster_to_be_accepted: 4
      dataloader_params:
          batch_size: 100
          num_workers: 6
  csv_folder: 'condda_results'
save_dir: "{workdir.id}"
harness_config:
  api_url: 'http://3.32.8.161:5001/'
  data_dir: ''
  gt_dir: ''
  gt_config: ''
