# @package _group_
protocol: 'ond'
workdir: ''
harness: 'local'
domain: "image_classification"
test_ids:
- "OND.54011215.0000.1236"
hints:
- "red_light"
use_feedback: True
dataset_root: ""
detectors:
  has_reaction_baseline: True
  has_baseline: False
  csv_folder: image_classification
  baseline_class: "BaselineImageClassifier"
  detector_configs:
    BaselineImageClassifier:
      model_name: "resnet50"
      checkpoint_path: ""
      image_size: 256
      crop_size: 224
      batch_size: 100
      num_workers: 6
      num_classes: 413
      use_gpu: True
    OND_12_With_Redlight:
      efficientnet_params:
          model_path: ""
          known_classes: 413
          image_size: 300
      evm_params:
          model_path: ""
          tailsize: 40000
          cover_threshold: 0.7
          distance_multiplier: 0.55
          distance_function: "cosine"
          mu_train: 1.0
          sigma_train: 0.1872130436656377
          KL_threshold: 7.13040406025555
          known_threshold: 0.7
      dataloader_params:
          batch_size: 100
          num_workers: 20
      feedback_params:
          first_budget: 10
          income_per_batch: 10
          maximum_budget: 10
      classification_params:
          alpha: 1.0
          flag_only_evm: 1
  save_elementwise: False
  save_attributes: False
  use_saved_attributes: False
save_dir: "{workdir.id}"
harness_config:
  url: 'http://3.32.8.161:5001/'
  data_dir: ''
  gt_dir: ''
  gt_config: ''
