# @package _group_
protocol: 'ond'
workdir: '/home/chris/code/sailon_tinker_launcher/workdir'
harness: 'local'
domain: image_classification
test_ids:
- OND.1.1.1234
detectors:
  has_reaction_baseline: 'False'
  has_baseline: 'False'
  detector_configs:
    MockDetector
